// doc.go
//
// Copyright (c) 2023-2024 Junpei Kawamoto
//
// This software is released under the MIT License.
//
// http://opensource.org/licenses/mit-license.php

// Package civitai consists of two sub-packages: client and models.
// client provides a [Civitai API] client, and models provides structures used in the client.
//
// Both packages are generated by [go-swagger]. See their docs to find the general usage of this client.
//
// [Civitai API]: https://github.com/civitai/civitai/wiki/REST-API-Reference
// [go-swagger]: https://github.com/go-swagger/go-swagger
//
//go:generate go run github.com/go-swagger/go-swagger/cmd/swagger@v0.31.0 generate client -f ./openapi.yaml -t .
package civitai
