// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-civitai/models"
)

// GetCreatorsReader is a Reader for the GetCreators structure.
type GetCreatorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCreatorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCreatorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCreatorsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCreatorsOK creates a GetCreatorsOK with default headers values
func NewGetCreatorsOK() *GetCreatorsOK {
	return &GetCreatorsOK{}
}

/*
GetCreatorsOK describes a response with status code 200, with default header values.

A list of creators.
*/
type GetCreatorsOK struct {
	Payload *models.CreatorsResponse
}

// IsSuccess returns true when this get creators o k response has a 2xx status code
func (o *GetCreatorsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get creators o k response has a 3xx status code
func (o *GetCreatorsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get creators o k response has a 4xx status code
func (o *GetCreatorsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get creators o k response has a 5xx status code
func (o *GetCreatorsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get creators o k response a status code equal to that given
func (o *GetCreatorsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get creators o k response
func (o *GetCreatorsOK) Code() int {
	return 200
}

func (o *GetCreatorsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /creators][%d] getCreatorsOK %s", 200, payload)
}

func (o *GetCreatorsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /creators][%d] getCreatorsOK %s", 200, payload)
}

func (o *GetCreatorsOK) GetPayload() *models.CreatorsResponse {
	return o.Payload
}

func (o *GetCreatorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatorsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCreatorsDefault creates a GetCreatorsDefault with default headers values
func NewGetCreatorsDefault(code int) *GetCreatorsDefault {
	return &GetCreatorsDefault{
		_statusCode: code,
	}
}

/*
GetCreatorsDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetCreatorsDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get creators default response has a 2xx status code
func (o *GetCreatorsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get creators default response has a 3xx status code
func (o *GetCreatorsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get creators default response has a 4xx status code
func (o *GetCreatorsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get creators default response has a 5xx status code
func (o *GetCreatorsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get creators default response a status code equal to that given
func (o *GetCreatorsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get creators default response
func (o *GetCreatorsDefault) Code() int {
	return o._statusCode
}

func (o *GetCreatorsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /creators][%d] getCreators default %s", o._statusCode, payload)
}

func (o *GetCreatorsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /creators][%d] getCreators default %s", o._statusCode, payload)
}

func (o *GetCreatorsDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetCreatorsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
