// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-civitai/models"
)

// GetModelVersionByHashReader is a Reader for the GetModelVersionByHash structure.
type GetModelVersionByHashReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelVersionByHashReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelVersionByHashOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetModelVersionByHashDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetModelVersionByHashOK creates a GetModelVersionByHashOK with default headers values
func NewGetModelVersionByHashOK() *GetModelVersionByHashOK {
	return &GetModelVersionByHashOK{}
}

/*
GetModelVersionByHashOK describes a response with status code 200, with default header values.

The model version info.
*/
type GetModelVersionByHashOK struct {
	Payload *models.ModelVersion
}

// IsSuccess returns true when this get model version by hash o k response has a 2xx status code
func (o *GetModelVersionByHashOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get model version by hash o k response has a 3xx status code
func (o *GetModelVersionByHashOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get model version by hash o k response has a 4xx status code
func (o *GetModelVersionByHashOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get model version by hash o k response has a 5xx status code
func (o *GetModelVersionByHashOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get model version by hash o k response a status code equal to that given
func (o *GetModelVersionByHashOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get model version by hash o k response
func (o *GetModelVersionByHashOK) Code() int {
	return 200
}

func (o *GetModelVersionByHashOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /model-versions/by-hash/{hash}][%d] getModelVersionByHashOK %s", 200, payload)
}

func (o *GetModelVersionByHashOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /model-versions/by-hash/{hash}][%d] getModelVersionByHashOK %s", 200, payload)
}

func (o *GetModelVersionByHashOK) GetPayload() *models.ModelVersion {
	return o.Payload
}

func (o *GetModelVersionByHashOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelVersionByHashDefault creates a GetModelVersionByHashDefault with default headers values
func NewGetModelVersionByHashDefault(code int) *GetModelVersionByHashDefault {
	return &GetModelVersionByHashDefault{
		_statusCode: code,
	}
}

/*
GetModelVersionByHashDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetModelVersionByHashDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get model version by hash default response has a 2xx status code
func (o *GetModelVersionByHashDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get model version by hash default response has a 3xx status code
func (o *GetModelVersionByHashDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get model version by hash default response has a 4xx status code
func (o *GetModelVersionByHashDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get model version by hash default response has a 5xx status code
func (o *GetModelVersionByHashDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get model version by hash default response a status code equal to that given
func (o *GetModelVersionByHashDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get model version by hash default response
func (o *GetModelVersionByHashDefault) Code() int {
	return o._statusCode
}

func (o *GetModelVersionByHashDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /model-versions/by-hash/{hash}][%d] getModelVersionByHash default %s", o._statusCode, payload)
}

func (o *GetModelVersionByHashDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /model-versions/by-hash/{hash}][%d] getModelVersionByHash default %s", o._statusCode, payload)
}

func (o *GetModelVersionByHashDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetModelVersionByHashDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
