// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetModelVersionByHashParams creates a new GetModelVersionByHashParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetModelVersionByHashParams() *GetModelVersionByHashParams {
	return &GetModelVersionByHashParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetModelVersionByHashParamsWithTimeout creates a new GetModelVersionByHashParams object
// with the ability to set a timeout on a request.
func NewGetModelVersionByHashParamsWithTimeout(timeout time.Duration) *GetModelVersionByHashParams {
	return &GetModelVersionByHashParams{
		timeout: timeout,
	}
}

// NewGetModelVersionByHashParamsWithContext creates a new GetModelVersionByHashParams object
// with the ability to set a context for a request.
func NewGetModelVersionByHashParamsWithContext(ctx context.Context) *GetModelVersionByHashParams {
	return &GetModelVersionByHashParams{
		Context: ctx,
	}
}

// NewGetModelVersionByHashParamsWithHTTPClient creates a new GetModelVersionByHashParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetModelVersionByHashParamsWithHTTPClient(client *http.Client) *GetModelVersionByHashParams {
	return &GetModelVersionByHashParams{
		HTTPClient: client,
	}
}

/*
GetModelVersionByHashParams contains all the parameters to send to the API endpoint

	for the get model version by hash operation.

	Typically these are written to a http.Request.
*/
type GetModelVersionByHashParams struct {

	// Hash.
	Hash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get model version by hash params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelVersionByHashParams) WithDefaults() *GetModelVersionByHashParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get model version by hash params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelVersionByHashParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get model version by hash params
func (o *GetModelVersionByHashParams) WithTimeout(timeout time.Duration) *GetModelVersionByHashParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get model version by hash params
func (o *GetModelVersionByHashParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get model version by hash params
func (o *GetModelVersionByHashParams) WithContext(ctx context.Context) *GetModelVersionByHashParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get model version by hash params
func (o *GetModelVersionByHashParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get model version by hash params
func (o *GetModelVersionByHashParams) WithHTTPClient(client *http.Client) *GetModelVersionByHashParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get model version by hash params
func (o *GetModelVersionByHashParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHash adds the hash to the get model version by hash params
func (o *GetModelVersionByHashParams) WithHash(hash string) *GetModelVersionByHashParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get model version by hash params
func (o *GetModelVersionByHashParams) SetHash(hash string) {
	o.Hash = hash
}

// WriteToRequest writes these params to a swagger request
func (o *GetModelVersionByHashParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hash
	if err := r.SetPathParam("hash", o.Hash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
