// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-civitai/models"
)

// GetModelVersionReader is a Reader for the GetModelVersion structure.
type GetModelVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetModelVersionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetModelVersionOK creates a GetModelVersionOK with default headers values
func NewGetModelVersionOK() *GetModelVersionOK {
	return &GetModelVersionOK{}
}

/*
GetModelVersionOK describes a response with status code 200, with default header values.

The model version info.
*/
type GetModelVersionOK struct {
	Payload *models.ModelVersion
}

// IsSuccess returns true when this get model version o k response has a 2xx status code
func (o *GetModelVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get model version o k response has a 3xx status code
func (o *GetModelVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get model version o k response has a 4xx status code
func (o *GetModelVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get model version o k response has a 5xx status code
func (o *GetModelVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get model version o k response a status code equal to that given
func (o *GetModelVersionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get model version o k response
func (o *GetModelVersionOK) Code() int {
	return 200
}

func (o *GetModelVersionOK) Error() string {
	return fmt.Sprintf("[GET /model-versions/{modelVersionId}][%d] getModelVersionOK  %+v", 200, o.Payload)
}

func (o *GetModelVersionOK) String() string {
	return fmt.Sprintf("[GET /model-versions/{modelVersionId}][%d] getModelVersionOK  %+v", 200, o.Payload)
}

func (o *GetModelVersionOK) GetPayload() *models.ModelVersion {
	return o.Payload
}

func (o *GetModelVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelVersionDefault creates a GetModelVersionDefault with default headers values
func NewGetModelVersionDefault(code int) *GetModelVersionDefault {
	return &GetModelVersionDefault{
		_statusCode: code,
	}
}

/*
GetModelVersionDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetModelVersionDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get model version default response has a 2xx status code
func (o *GetModelVersionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get model version default response has a 3xx status code
func (o *GetModelVersionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get model version default response has a 4xx status code
func (o *GetModelVersionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get model version default response has a 5xx status code
func (o *GetModelVersionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get model version default response a status code equal to that given
func (o *GetModelVersionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get model version default response
func (o *GetModelVersionDefault) Code() int {
	return o._statusCode
}

func (o *GetModelVersionDefault) Error() string {
	return fmt.Sprintf("[GET /model-versions/{modelVersionId}][%d] getModelVersion default  %+v", o._statusCode, o.Payload)
}

func (o *GetModelVersionDefault) String() string {
	return fmt.Sprintf("[GET /model-versions/{modelVersionId}][%d] getModelVersion default  %+v", o._statusCode, o.Payload)
}

func (o *GetModelVersionDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetModelVersionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
