// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTagsParams creates a new GetTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTagsParams() *GetTagsParams {
	return &GetTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagsParamsWithTimeout creates a new GetTagsParams object
// with the ability to set a timeout on a request.
func NewGetTagsParamsWithTimeout(timeout time.Duration) *GetTagsParams {
	return &GetTagsParams{
		timeout: timeout,
	}
}

// NewGetTagsParamsWithContext creates a new GetTagsParams object
// with the ability to set a context for a request.
func NewGetTagsParamsWithContext(ctx context.Context) *GetTagsParams {
	return &GetTagsParams{
		Context: ctx,
	}
}

// NewGetTagsParamsWithHTTPClient creates a new GetTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTagsParamsWithHTTPClient(client *http.Client) *GetTagsParams {
	return &GetTagsParams{
		HTTPClient: client,
	}
}

/*
GetTagsParams contains all the parameters to send to the API endpoint

	for the get tags operation.

	Typically these are written to a http.Request.
*/
type GetTagsParams struct {

	/* Limit.

	   The number of results to be returned per page. This can be a number between 1 and 200. By default, each page will return 20 results. If set to 0, it'll return all the tags.

	   Format: int64
	   Default: 20
	*/
	Limit *int64

	/* Page.

	   The page from which to start fetching tags.

	   Format: int64
	*/
	Page *int64

	/* Query.

	   Search query to filter tags by name.
	*/
	Query *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTagsParams) WithDefaults() *GetTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTagsParams) SetDefaults() {
	var (
		limitDefault = int64(20)
	)

	val := GetTagsParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get tags params
func (o *GetTagsParams) WithTimeout(timeout time.Duration) *GetTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tags params
func (o *GetTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tags params
func (o *GetTagsParams) WithContext(ctx context.Context) *GetTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tags params
func (o *GetTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tags params
func (o *GetTagsParams) WithHTTPClient(client *http.Client) *GetTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tags params
func (o *GetTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get tags params
func (o *GetTagsParams) WithLimit(limit *int64) *GetTagsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get tags params
func (o *GetTagsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get tags params
func (o *GetTagsParams) WithPage(page *int64) *GetTagsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get tags params
func (o *GetTagsParams) SetPage(page *int64) {
	o.Page = page
}

// WithQuery adds the query to the get tags params
func (o *GetTagsParams) WithQuery(query *string) *GetTagsParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the get tags params
func (o *GetTagsParams) SetQuery(query *string) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.Query != nil {

		// query param query
		var qrQuery string

		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {

			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
