// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetModelVersionParams creates a new GetModelVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetModelVersionParams() *GetModelVersionParams {
	return &GetModelVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetModelVersionParamsWithTimeout creates a new GetModelVersionParams object
// with the ability to set a timeout on a request.
func NewGetModelVersionParamsWithTimeout(timeout time.Duration) *GetModelVersionParams {
	return &GetModelVersionParams{
		timeout: timeout,
	}
}

// NewGetModelVersionParamsWithContext creates a new GetModelVersionParams object
// with the ability to set a context for a request.
func NewGetModelVersionParamsWithContext(ctx context.Context) *GetModelVersionParams {
	return &GetModelVersionParams{
		Context: ctx,
	}
}

// NewGetModelVersionParamsWithHTTPClient creates a new GetModelVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetModelVersionParamsWithHTTPClient(client *http.Client) *GetModelVersionParams {
	return &GetModelVersionParams{
		HTTPClient: client,
	}
}

/*
GetModelVersionParams contains all the parameters to send to the API endpoint

	for the get model version operation.

	Typically these are written to a http.Request.
*/
type GetModelVersionParams struct {

	// ModelVersionID.
	//
	// Format: int64
	ModelVersionID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get model version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelVersionParams) WithDefaults() *GetModelVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get model version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get model version params
func (o *GetModelVersionParams) WithTimeout(timeout time.Duration) *GetModelVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get model version params
func (o *GetModelVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get model version params
func (o *GetModelVersionParams) WithContext(ctx context.Context) *GetModelVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get model version params
func (o *GetModelVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get model version params
func (o *GetModelVersionParams) WithHTTPClient(client *http.Client) *GetModelVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get model version params
func (o *GetModelVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModelVersionID adds the modelVersionID to the get model version params
func (o *GetModelVersionParams) WithModelVersionID(modelVersionID int64) *GetModelVersionParams {
	o.SetModelVersionID(modelVersionID)
	return o
}

// SetModelVersionID adds the modelVersionId to the get model version params
func (o *GetModelVersionParams) SetModelVersionID(modelVersionID int64) {
	o.ModelVersionID = modelVersionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetModelVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param modelVersionId
	if err := r.SetPathParam("modelVersionId", swag.FormatInt64(o.ModelVersionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
