// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-civitai/models"
)

// GetImagesReader is a Reader for the GetImages structure.
type GetImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetImagesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetImagesOK creates a GetImagesOK with default headers values
func NewGetImagesOK() *GetImagesOK {
	return &GetImagesOK{}
}

/*
GetImagesOK describes a response with status code 200, with default header values.

A list of images.
*/
type GetImagesOK struct {
	Payload *models.ImagesResponse
}

// IsSuccess returns true when this get images o k response has a 2xx status code
func (o *GetImagesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get images o k response has a 3xx status code
func (o *GetImagesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get images o k response has a 4xx status code
func (o *GetImagesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get images o k response has a 5xx status code
func (o *GetImagesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get images o k response a status code equal to that given
func (o *GetImagesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get images o k response
func (o *GetImagesOK) Code() int {
	return 200
}

func (o *GetImagesOK) Error() string {
	return fmt.Sprintf("[GET /images][%d] getImagesOK  %+v", 200, o.Payload)
}

func (o *GetImagesOK) String() string {
	return fmt.Sprintf("[GET /images][%d] getImagesOK  %+v", 200, o.Payload)
}

func (o *GetImagesOK) GetPayload() *models.ImagesResponse {
	return o.Payload
}

func (o *GetImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImagesDefault creates a GetImagesDefault with default headers values
func NewGetImagesDefault(code int) *GetImagesDefault {
	return &GetImagesDefault{
		_statusCode: code,
	}
}

/*
GetImagesDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetImagesDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get images default response has a 2xx status code
func (o *GetImagesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get images default response has a 3xx status code
func (o *GetImagesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get images default response has a 4xx status code
func (o *GetImagesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get images default response has a 5xx status code
func (o *GetImagesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get images default response a status code equal to that given
func (o *GetImagesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get images default response
func (o *GetImagesDefault) Code() int {
	return o._statusCode
}

func (o *GetImagesDefault) Error() string {
	return fmt.Sprintf("[GET /images][%d] getImages default  %+v", o._statusCode, o.Payload)
}

func (o *GetImagesDefault) String() string {
	return fmt.Sprintf("[GET /images][%d] getImages default  %+v", o._statusCode, o.Payload)
}

func (o *GetImagesDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetImagesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
