// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-civitai/models"
)

// GetTagsReader is a Reader for the GetTags structure.
type GetTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetTagsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTagsOK creates a GetTagsOK with default headers values
func NewGetTagsOK() *GetTagsOK {
	return &GetTagsOK{}
}

/*
GetTagsOK describes a response with status code 200, with default header values.

A list of tags.
*/
type GetTagsOK struct {
	Payload *models.TagsResponse
}

// IsSuccess returns true when this get tags o k response has a 2xx status code
func (o *GetTagsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tags o k response has a 3xx status code
func (o *GetTagsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tags o k response has a 4xx status code
func (o *GetTagsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tags o k response has a 5xx status code
func (o *GetTagsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tags o k response a status code equal to that given
func (o *GetTagsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get tags o k response
func (o *GetTagsOK) Code() int {
	return 200
}

func (o *GetTagsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags][%d] getTagsOK %s", 200, payload)
}

func (o *GetTagsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags][%d] getTagsOK %s", 200, payload)
}

func (o *GetTagsOK) GetPayload() *models.TagsResponse {
	return o.Payload
}

func (o *GetTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TagsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTagsDefault creates a GetTagsDefault with default headers values
func NewGetTagsDefault(code int) *GetTagsDefault {
	return &GetTagsDefault{
		_statusCode: code,
	}
}

/*
GetTagsDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetTagsDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get tags default response has a 2xx status code
func (o *GetTagsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get tags default response has a 3xx status code
func (o *GetTagsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get tags default response has a 4xx status code
func (o *GetTagsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get tags default response has a 5xx status code
func (o *GetTagsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get tags default response a status code equal to that given
func (o *GetTagsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get tags default response
func (o *GetTagsDefault) Code() int {
	return o._statusCode
}

func (o *GetTagsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags][%d] getTags default %s", o._statusCode, payload)
}

func (o *GetTagsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags][%d] getTags default %s", o._statusCode, payload)
}

func (o *GetTagsDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetTagsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
