// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Creator creator
//
// swagger:model Creator
type Creator struct {

	// Url to get all models from this user.
	// Example: https://civitai.com/api/v1/models?username=Civitai
	Link string `json:"link,omitempty"`

	// The amount of models linked to this user.
	// Example: 848
	ModelCount int64 `json:"modelCount,omitempty"`

	// The username of the creator.
	// Example: Civitai
	Username string `json:"username,omitempty"`
}

// Validate validates this creator
func (m *Creator) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this creator based on context it is used
func (m *Creator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Creator) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Creator) UnmarshalBinary(b []byte) error {
	var res Creator
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
