// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FileMetadata file metadata
//
// swagger:model FileMetadata
type FileMetadata struct {

	// format
	Format string `json:"format,omitempty"`

	// fp
	Fp string `json:"fp,omitempty"`

	// size
	Size string `json:"size,omitempty"`
}

// Validate validates this file metadata
func (m *FileMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this file metadata based on context it is used
func (m *FileMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FileMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FileMetadata) UnmarshalBinary(b []byte) error {
	var res FileMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
