// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Model model
//
// swagger:model Model
type Model struct {

	// allow commercial use
	AllowCommercialUse string `json:"allowCommercialUse,omitempty"`

	// allow derivatives
	AllowDerivatives bool `json:"allowDerivatives,omitempty"`

	// allow different license
	AllowDifferentLicense bool `json:"allowDifferentLicense,omitempty"`

	// allow no credit
	AllowNoCredit bool `json:"allowNoCredit,omitempty"`

	// creator
	Creator *ModelCreator `json:"creator,omitempty"`

	// The description of the model (HTML).
	Description string `json:"description,omitempty"`

	// The identifier for the model.
	ID int64 `json:"id,omitempty"`

	// model versions
	ModelVersions []*ModelVersion `json:"modelVersions"`

	// The name of the model.
	Name string `json:"name,omitempty"`

	// Whether the model is NSFW or not.
	Nsfw bool `json:"nsfw,omitempty"`

	// poi
	Poi bool `json:"poi,omitempty"`

	// rank
	Rank *Rank `json:"rank,omitempty"`

	// stats
	Stats *Stats `json:"stats,omitempty"`

	// The tags associated with the model.
	Tags []string `json:"tags"`

	// The model type.
	// Enum: [Checkpoint TextualInversion Hypernetwork AestheticGradient LORA LyCORIS Controlnet Wildcards Poses Other]
	Type string `json:"type,omitempty"`
}

// Validate validates this model
func (m *Model) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModelVersions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRank(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStats(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Model) validateCreator(formats strfmt.Registry) error {
	if swag.IsZero(m.Creator) { // not required
		return nil
	}

	if m.Creator != nil {
		if err := m.Creator.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("creator")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("creator")
			}
			return err
		}
	}

	return nil
}

func (m *Model) validateModelVersions(formats strfmt.Registry) error {
	if swag.IsZero(m.ModelVersions) { // not required
		return nil
	}

	for i := 0; i < len(m.ModelVersions); i++ {
		if swag.IsZero(m.ModelVersions[i]) { // not required
			continue
		}

		if m.ModelVersions[i] != nil {
			if err := m.ModelVersions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("modelVersions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("modelVersions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Model) validateRank(formats strfmt.Registry) error {
	if swag.IsZero(m.Rank) { // not required
		return nil
	}

	if m.Rank != nil {
		if err := m.Rank.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rank")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rank")
			}
			return err
		}
	}

	return nil
}

func (m *Model) validateStats(formats strfmt.Registry) error {
	if swag.IsZero(m.Stats) { // not required
		return nil
	}

	if m.Stats != nil {
		if err := m.Stats.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stats")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stats")
			}
			return err
		}
	}

	return nil
}

var modelTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Checkpoint","TextualInversion","Hypernetwork","AestheticGradient","LORA","LyCORIS","Controlnet","Wildcards","Poses","Other"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		modelTypeTypePropEnum = append(modelTypeTypePropEnum, v)
	}
}

const (

	// ModelTypeCheckpoint captures enum value "Checkpoint"
	ModelTypeCheckpoint string = "Checkpoint"

	// ModelTypeTextualInversion captures enum value "TextualInversion"
	ModelTypeTextualInversion string = "TextualInversion"

	// ModelTypeHypernetwork captures enum value "Hypernetwork"
	ModelTypeHypernetwork string = "Hypernetwork"

	// ModelTypeAestheticGradient captures enum value "AestheticGradient"
	ModelTypeAestheticGradient string = "AestheticGradient"

	// ModelTypeLORA captures enum value "LORA"
	ModelTypeLORA string = "LORA"

	// ModelTypeLyCORIS captures enum value "LyCORIS"
	ModelTypeLyCORIS string = "LyCORIS"

	// ModelTypeControlnet captures enum value "Controlnet"
	ModelTypeControlnet string = "Controlnet"

	// ModelTypeWildcards captures enum value "Wildcards"
	ModelTypeWildcards string = "Wildcards"

	// ModelTypePoses captures enum value "Poses"
	ModelTypePoses string = "Poses"

	// ModelTypeOther captures enum value "Other"
	ModelTypeOther string = "Other"
)

// prop value enum
func (m *Model) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, modelTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Model) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this model based on the context it is used
func (m *Model) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreator(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateModelVersions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRank(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Model) contextValidateCreator(ctx context.Context, formats strfmt.Registry) error {

	if m.Creator != nil {
		if err := m.Creator.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("creator")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("creator")
			}
			return err
		}
	}

	return nil
}

func (m *Model) contextValidateModelVersions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ModelVersions); i++ {

		if m.ModelVersions[i] != nil {
			if err := m.ModelVersions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("modelVersions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("modelVersions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Model) contextValidateRank(ctx context.Context, formats strfmt.Registry) error {

	if m.Rank != nil {
		if err := m.Rank.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rank")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rank")
			}
			return err
		}
	}

	return nil
}

func (m *Model) contextValidateStats(ctx context.Context, formats strfmt.Registry) error {

	if m.Stats != nil {
		if err := m.Stats.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stats")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stats")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Model) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Model) UnmarshalBinary(b []byte) error {
	var res Model
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
