// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelCreator model creator
//
// swagger:model ModelCreator
type ModelCreator struct {

	// The url of the creators avatar.
	Image string `json:"image,omitempty"`

	// The name of the creator.
	Username string `json:"username,omitempty"`
}

// Validate validates this model creator
func (m *ModelCreator) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model creator based on context it is used
func (m *ModelCreator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelCreator) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelCreator) UnmarshalBinary(b []byte) error {
	var res ModelCreator
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
