// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Rank rank
//
// swagger:model Rank
type Rank struct {

	// comment count all time
	CommentCountAllTime int64 `json:"commentCountAllTime,omitempty"`

	// download count all time
	DownloadCountAllTime int64 `json:"downloadCountAllTime,omitempty"`

	// favorite count all time
	FavoriteCountAllTime int64 `json:"favoriteCountAllTime,omitempty"`

	// rating all time
	RatingAllTime float64 `json:"ratingAllTime,omitempty"`

	// rating count all time
	RatingCountAllTime int64 `json:"ratingCountAllTime,omitempty"`
}

// Validate validates this rank
func (m *Rank) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rank based on context it is used
func (m *Rank) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Rank) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Rank) UnmarshalBinary(b []byte) error {
	var res Rank
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
